/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhojavaav2.Interfaces;

import java.util.ArrayList;
import trabalhojavaav2.Arquivos.ArquivoVendas;
import trabalhojavaav2.Classes.Venda;
import trabalhojavaav2.ModelosTabela.ModeloTabelaVenda;
import trabalhojavaav2.OperacaoCadastro;

/**
 *
 * @author vitor
 */
public class MenuVendas extends javax.swing.JDialog {

    private ArquivoVendas arquivo;
    private ModeloTabelaVenda modeloVenda;
    
    public MenuVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        arquivo = new ArquivoVendas("Vendas.txt");
        modeloVenda = new ModeloTabelaVenda(new ArrayList<Venda>());
        tabVendas.setModel(modeloVenda);
        abrirTxt();
        abrirSaldo();
    }
    
    private void abrirTxt() {
        try {
            ArrayList <Venda> vendas = new ArrayList<Venda>();
            vendas = arquivo.abrirTxt();
            for (int i = 0; i < vendas.size(); i++) {
                Venda venda = vendas.get(i);
                modeloVenda.incluirVenda(venda);
            }
        } catch (NullPointerException e) {
            System.err.println(e.getMessage());
        }
    }
    
    private void abrirSaldo() {
        try {
            ArrayList <Venda> vendas = new ArrayList <Venda>();
            vendas = arquivo.abrirTxt();
            float saldo = 0;
            for (int i = 0; i < vendas.size(); i++) {
                saldo += vendas.get(i).obterPrecoTotal();
            }
            rotuloSaldo.setText(String.valueOf(saldo));
        } catch (NullPointerException e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVendas = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        buCadastrarVenda = new javax.swing.JButton();
        buSelecionarVenda = new javax.swing.JButton();
        buVoltarVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rotuloSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jScrollPane1.setViewportView(tabVendas);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buCadastrarVenda.setText("Inserir");
        buCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCadastrarVendaActionPerformed(evt);
            }
        });

        buSelecionarVenda.setText("Consultar");
        buSelecionarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSelecionarVendaActionPerformed(evt);
            }
        });

        buVoltarVenda.setText("Voltar");
        buVoltarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buVoltarVendaActionPerformed(evt);
            }
        });

        jLabel1.setText("Saldo:");

        rotuloSaldo.setText("0");
        rotuloSaldo.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buCadastrarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buSelecionarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(buVoltarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rotuloSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(buCadastrarVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buSelecionarVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buVoltarVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rotuloSaldo))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buVoltarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buVoltarVendaActionPerformed
        dispose();
    }//GEN-LAST:event_buVoltarVendaActionPerformed

    private void buCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCadastrarVendaActionPerformed
        Venda venda = new Venda();
        if (MenuCadVenda.executar(null, OperacaoCadastro.ocIncluir, venda)) {
            modeloVenda.incluirVenda(venda);
            arquivo.salvarEmTxt(modeloVenda.obterTodasVendas());
            abrirSaldo();
        }
    }//GEN-LAST:event_buCadastrarVendaActionPerformed

    private void buSelecionarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSelecionarVendaActionPerformed
        int indice = tabVendas.getSelectedRow();
        if (indice >= 0) {
            setVisible(false);
            MenuItemVenda menuItemVenda = new MenuItemVenda(null, true, OperacaoCadastro.ocConsultar, modeloVenda.obterVenda(indice));
            menuItemVenda.setLocationRelativeTo(null);
            menuItemVenda.setVisible(true);
            setVisible(true);
        }
    }//GEN-LAST:event_buSelecionarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuVendas dialog = new MenuVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buCadastrarVenda;
    private javax.swing.JButton buSelecionarVenda;
    private javax.swing.JButton buVoltarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel rotuloSaldo;
    private javax.swing.JTable tabVendas;
    // End of variables declaration//GEN-END:variables
}
