package trabalhojavaav2.Interfaces;

import javax.swing.JOptionPane;
import trabalhojavaav2.Classes.Produto;
import trabalhojavaav2.OperacaoCadastro;

/**
 *
 * @author vitor
 */

public class MenuCadProduto extends javax.swing.JDialog {

    private OperacaoCadastro operacaoCadastro;
    private Produto produto;
    private boolean confirmado;
    
    public MenuCadProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public MenuCadProduto(java.awt.Frame parent, OperacaoCadastro operacaoCadastro, Produto produto) {
        super (parent, true);
        this.operacaoCadastro=operacaoCadastro;
        this.produto=produto;
        confirmado=false;
        initComponents();
        if (operacaoCadastro == OperacaoCadastro.ocAlterar || operacaoCadastro == OperacaoCadastro.ocConsultar) {
            textCodigoProd.setText(String.valueOf(produto.obterCodigo()));
            textNomeProd.setText(produto.obterNome());
            textPrecoProd.setText(String.valueOf(produto.obterPreco()));
            textEstoqueProd.setText(String.valueOf(produto.obterEstoque()));
        }
        buCancelarProd.setEnabled(operacaoCadastro != OperacaoCadastro.ocConsultar);
        textCodigoProd.setEnabled(false);
        textNomeProd.setEnabled(operacaoCadastro != OperacaoCadastro.ocConsultar);
        textPrecoProd.setEnabled(operacaoCadastro != OperacaoCadastro.ocConsultar);
        textEstoqueProd.setEnabled(operacaoCadastro != OperacaoCadastro.ocConsultar);
    }
    
    public boolean operacaoConfirmada() {
        return confirmado;
    }
    
    public static boolean executar(java.awt.Frame parent, OperacaoCadastro operacaoCadastro, Produto produto) {
        MenuCadProduto menuCadProdutos = new MenuCadProduto(parent, operacaoCadastro, produto);
        menuCadProdutos.setLocationRelativeTo(null);
        menuCadProdutos.setVisible(true);
        return menuCadProdutos.operacaoConfirmada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buOkProd = new javax.swing.JButton();
        buCancelarProd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textNomeProd = new javax.swing.JTextField();
        textPrecoProd = new javax.swing.JTextField();
        textEstoqueProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textCodigoProd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel2.setText("*Preço:");

        jLabel3.setText("*Nome:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buOkProd.setText("Ok");
        buOkProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buOkProdActionPerformed(evt);
            }
        });

        buCancelarProd.setText("Cancelar");
        buCancelarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCancelarProdActionPerformed(evt);
            }
        });

        jLabel5.setText("*Estoque:");

        jLabel1.setText("Código:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(textPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textCodigoProd)
                            .addComponent(textNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textEstoqueProd, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buOkProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buCancelarProd))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(buOkProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buCancelarProd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel4)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCodigoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEstoqueProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buCancelarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCancelarProdActionPerformed
        dispose();
    }//GEN-LAST:event_buCancelarProdActionPerformed

    private void buOkProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buOkProdActionPerformed
        boolean valido = true;
        try {
            if (operacaoCadastro != OperacaoCadastro.ocConsultar) {
                
                String camposInvalidos[] = new String [4];
                int index = 1;
                
                if (!textNomeProd.getText().equals("")) {
                    produto.atualizarNome(textNomeProd.getText().toUpperCase());
                } else {
                    camposInvalidos[index++] = "Nome";
                    valido = false;
                }
                if (!textPrecoProd.getText().equals("")) {
                    produto.atualizarPreco(Float.parseFloat(textPrecoProd.getText()));
                } else {
                    camposInvalidos[index++] = "Preco";
                    valido = false;
                }
                if (!textEstoqueProd.getText().equals("")) {
                    produto.atualizarEstoque(Integer.parseInt(textEstoqueProd.getText()));
                } else {
                    camposInvalidos[index++] = "Estoque";
                    valido = false;
                }
                
                if (valido) {
                    confirmado = true;
                } else {
                    camposInvalidos[0] = "Entrada(s) Invalida(s):\n\n";
                    JOptionPane.showMessageDialog(this, camposInvalidos);
                }
                
            }
        }catch (Exception e) { 
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Entrada Invalida!\n"+e);
        }
        if (valido) {
            dispose();
        }
    }//GEN-LAST:event_buOkProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuCadProduto dialog = new MenuCadProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buCancelarProd;
    private javax.swing.JButton buOkProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textCodigoProd;
    private javax.swing.JTextField textEstoqueProd;
    private javax.swing.JTextField textNomeProd;
    private javax.swing.JTextField textPrecoProd;
    // End of variables declaration//GEN-END:variables
}
