/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhojavaav2.Interfaces;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import trabalhojavaav2.BancoDeDados.ProdutoBD;
import trabalhojavaav2.Classes.Produto;
import trabalhojavaav2.ModelosTabela.ModeloTabelaProduto;
import trabalhojavaav2.OperacaoCadastro;

/**
 *
 * @author vitor
 */
public class MenuProdutos extends javax.swing.JDialog {
    
    private ProdutoBD produtoBD;
    private ModeloTabelaProduto modeloProduto;
    
    public MenuProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        produtoBD = new ProdutoBD();
        modeloProduto = new ModeloTabelaProduto(new ArrayList<Produto>());
        tabProdutos.setModel(modeloProduto);
        atualizarModelo();
    }
    
    private void atualizarModelo() {
        try {
            ArrayList <Produto> produtos = new ArrayList<Produto>() ;
            produtos = produtoBD.lerProdutos();
            for (int i = 0; i < produtos.size(); i++) {
                Produto produto = produtos.get(i);
                modeloProduto.incluirProduto(produto);
            }
        } catch (NullPointerException e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProdutos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        buCadastrarProd = new javax.swing.JButton();
        buAlterarProd = new javax.swing.JButton();
        buExcluirProd = new javax.swing.JButton();
        buSelecionarProd = new javax.swing.JButton();
        buVoltarProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        tabProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabProdutos);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buCadastrarProd.setText("Inserir");
        buCadastrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCadastrarProdActionPerformed(evt);
            }
        });

        buAlterarProd.setText("Alterar");
        buAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAlterarProdActionPerformed(evt);
            }
        });

        buExcluirProd.setText("Excluir");
        buExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buExcluirProdActionPerformed(evt);
            }
        });

        buSelecionarProd.setText("Consultar");
        buSelecionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSelecionarProdActionPerformed(evt);
            }
        });

        buVoltarProd.setText("Voltar");
        buVoltarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buVoltarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buSelecionarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buExcluirProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buAlterarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buCadastrarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buVoltarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buCadastrarProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buAlterarProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buExcluirProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buSelecionarProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buVoltarProd)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buVoltarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buVoltarProdActionPerformed
        dispose();
    }//GEN-LAST:event_buVoltarProdActionPerformed

    private void buCadastrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCadastrarProdActionPerformed
        Produto produto = new Produto();
        if (MenuCadProduto.executar(null, OperacaoCadastro.ocIncluir, produto)) {
            modeloProduto.incluirProduto(produtoBD.inserirProduto(produto));
        }
    }//GEN-LAST:event_buCadastrarProdActionPerformed

    private void buAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAlterarProdActionPerformed
        int indice = tabProdutos.getSelectedRow();
        if (indice >= 0) {
            Produto produto = modeloProduto.obterProduto(indice);
            if (MenuCadProduto.executar(null, OperacaoCadastro.ocAlterar, produto)) {
                produtoBD.alterarProduto(produto);
                modeloProduto.atualizarProduto(indice, produto);
            }
        }
    }//GEN-LAST:event_buAlterarProdActionPerformed

    private void buExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buExcluirProdActionPerformed
        int indice = tabProdutos.getSelectedRow();
        if (indice >= 0) {
            Produto produto = modeloProduto.obterProduto(indice);
            int opcao = JOptionPane.showConfirmDialog(this, "Confirmar Exclusao de:  "+produto.obterNome(), "Exclusao", 
                                                      JOptionPane.YES_NO_OPTION);
            if (opcao == 0) {
                produtoBD.excluirProduto(produto);
                modeloProduto.excluirProduto(indice);
            }
        }
    }//GEN-LAST:event_buExcluirProdActionPerformed

    private void buSelecionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSelecionarProdActionPerformed
        int indice = tabProdutos.getSelectedRow();
        if (indice >= 0) {
            Produto produto = modeloProduto.obterProduto(indice);
            MenuCadProduto.executar(null, OperacaoCadastro.ocConsultar, produto);
        }
    }//GEN-LAST:event_buSelecionarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuProdutos dialog = new MenuProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buAlterarProd;
    private javax.swing.JButton buCadastrarProd;
    private javax.swing.JButton buExcluirProd;
    private javax.swing.JButton buSelecionarProd;
    private javax.swing.JButton buVoltarProd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabProdutos;
    // End of variables declaration//GEN-END:variables
}
